### PR TITLE
fixed core dumps and other changes

### PR DESCRIPTION
**Pull request by s-p-k**
I fixed core dumps and I think I ensure that procstat is called properly. I also parse arguments inside main. I believe these changes make sense.

### CODE REVIEW

**Comment by hayamiz** [comment]
Thanks very much for your refactoring :+1: 
Almost ok for merge, except for commit a70169d. I don't like long main function, so `parse_args` should be separated. Could you revert it, then I will merge the request.

**Comment by s-p-k** [comment]
You are welcome. I will revert as soon as possible(Easter holidays here) and make sure nothing breaks.

**Comment by s-p-k** [comment]
Hi again, I reverted back to previous commits. Please check if everything's fine for merge.

**Comment by hayamiz** [comment]
Thank you :+1:

**Pull request merged**
